SELECT DONDATHANG.MAKHACHHANG, DONDATHANG.SOHOADON, SUM(SOLUONG*GIABAN-SOLUONG*GIABAN*MUCGIAMGIA/100) AS TONGSOTIEN
FROM (KHACHHANG JOIN DONDATHANG ON KHACHHANG.MAKHACHHANG=DONDATHANG.MAKHACHHANG)
				JOIN CHITIETDATHANG ON CHITIETDATHANG.SOHOADON=DONDATHANG.SOHOADON
GROUP BY DONDATHANG.MAKHACHHANG,DONDATHANG.SOHOADON

SELECT C.MAHANG, TENHANG, TENCONGTY, SUM(B.SOLUONG*GIABAN-B.SOLUONG*GIABAN*MUCGIAMGIA/100)-SUM(B.SOLUONG*GIAHANG) AS GIATIENLOI
FROM (DONDATHANG AS A JOIN CHITIETDATHANG  AS B ON A.SOHOADON=B.SOHOADON) 
						JOIN MATHANG AS C ON B.MAHANG=C.MAHANG
						JOIN  NHACUNGCAP  ON NHACUNGCAP.MACONGTY=C.MACONGTY
WHERE YEAR(NGAYDATHANG)=2017
GROUP BY C.MAHANG, TENHANG, TENCONGTY
HAVING  SUM(B.SOLUONG*GIABAN-B.SOLUONG*GIABAN*MUCGIAMGIA/100)-SUM(B.SOLUONG*GIAHANG) < 0