select GIAOVIEN.*, TRUONGBM 
from GIAOVIEN join BOMON on GIAOVIEN.MABM=BOMON.MABM	
where GIAOVIEN.MABM=BOMON.MABM
select COUNT(GIAOVIEN.MAGV) as SLGV
from GIAOVIEN join BOMON on GIAOVIEN.MABM=BOMON.MABM
				join KHOA on KHOA.MAKHOA=BOMON.MAKHOA
where TENKHOA =N'Công nghệ thông tin'

select GIAOVIEN.*
from  GIAOVIEN JOIN THAMGIADT ON THAMGIADT.MAGV=GIAOVIEN.MAGV
WHERE KETQUA =N'Đạt'

SELECT *
FROM THAMGIADT join DETAI on THAMGIADT.MADT=DETAI.MADT