select NHACUNGCAP.MACONGTY, TENCONGTY, MAHANG, TENHANG
FROM NHACUNGCAP JOIN MATHANG ON NHACUNGCAP.MACONGTY = MATHANG.MACONGTY
	JOIN 

SELECT LOAIHANG.MALOAIHANG, TENLOAIHANG, NHACUNGCAP.MACONGTY,  TENCONGTY
FROM NHACUNGCAP JOIN MATHANG ON NHACUNGCAP.MACONGTY = MATHANG.MACONGTY
				JOIN LOAIHANG ON LOAIHANG.MALOAIHANG = MATHANG.MALOAIHANG 

SELECT HO, TEN , NGAYSINH, CHITIETDATHANG.MAHANG, TENHANG
FROM NHANVIEN  JOIN DONDATHANG ON NHANVIEN.MANHANVIEN = DONDATHANG.MANHANVIEN
			   JOIN CHITIETDATHANG ON CHITIETDATHANG.SOHOADON = DONDATHANG.SOHOADON
			   JOIN MATHANG ON MATHANG.MAHANG = CHITIETDATHANG.MAHANG

SELECT MAHANG,TENHANG,SOLUONG,GIAHANG
FROM MATHANG
WHERE
	SOLUONG > 50 AND GIAHANG < 10000
	--CHO BIET THONG TIN CAC NHANH VIEN CO HO LA HOANG--
	SELECT *
	FROM NHANVIEN
	where HO LIKE 'HOANG'


SELECT TENLOAIHANG , TENCONGTY, DIACHI, NHACUNGCAP.MACONGTY
FROM LOAIHANG JOIN MATHANG ON LOAIHANG.MALOAIHANG = MATHANG.MALOAIHANG
			  JOIN NHACUNGCAP ON NHACUNGCAP.MACONGTY = MATHANG.MACONGTY	
WHERE TENLOAIHANG LIKE N'Thực phẩm