UPDATE DONDATHANG
SET NGAYCHUYENHANG=NGAYDATHANG
FROM DONDATHANG
WHERE NGAYCHUYENHANG IS NULL


UPDATE MATHANG
SET SOLUONG*2
FROM MATHANG JOIN NHACUNGCAP ON MATHANG.MACONGTY=NHACUNGCAP.MACONGTY
WHERE NHACUNGCAP ='VINAMILK'

SELECT *
FROM MATHANG