//*5. 27 Nhân viên nào của công ty bán được số lượng hàng nhiều nhất và số lượng hàng
bán được của những nhân viên này là bao nhiêu? *//
SELECT NHANVIEN.MANHANVIEN, HO, TEN, SUM(SOLUONG) AS 'SOLUONGBANHANG'
FROM (NHANVIEN INNER JOIN DONDATHANG ON NHANVIEN.MANHANVIEN=DONDATHANG.MANHANVIEN)
			INNER JOIN CHITIETDATHANG ON CHITIETDATHANG.SOHOADON=DONDATHANG.SOHOADON 
GROUP BY NHANVIEN.MANHANVIEN, HO, TEN
HAVING SUM(SOLUONG) >= ALL(SELECT SUM(SOLUONG)
							FROM (NHANVIEN INNER JOIN DONDATHANG ON NHANVIEN.MANHANVIEN=DONDATHANG.MAKHACHHANG)
											INNER JOIN CHITIETDATHANG ON DONDATHANG.SOHOADON=CHITIETDATHANG.SOHOADON
							GROUP BY NHANVIEN.MANHANVIEN, HO, TEN)

//*5. 28 Đơn đặt hàng nào có số lượng hàng được đặt mua ít nhất?*//
SELECT DONDATHANG.SOHOADON, SUM(SOLUONG) AS 'SOLUONGMUA'
FROM DONDATHANG INNER JOIN CHITIETDATHANG ON DONDATHANG.SOHOADON=CHITIETDATHANG.SOHOADON
GROUP BY DONDATHANG.SOHOADON
HAVING SUM(SOLUONG) <= ALL(SELECT SUM(SOLUONG)
							FROM DONDATHANG INNER JOIN CHITIETDATHANG ON DONDATHANG.SOHOADON=CHITIETDATHANG.SOHOADON
							GROUP BY DONDATHANG.SOHOADON)
//*5. 29 Số tiền nhiều nhất mà mỗi khách hàng đã từng bỏ ra để đặt hàng trong các đơn
đặt hàng là bao nhiêu?*//
SELECT TOP 1 SUM(SOLUONG*GIABAN-SOLUONG*GIABAN*MUCGIAMGIA/100) AS 'SOTIENLONNNHAT'
FROM DONDATHANG INNER JOIN CHITIETDATHANG ON DONDATHANG.SOHOADON=CHITIETDATHANG.SOHOADON
ORDER BY 1 DESC
//*5. 30 Mỗi một đơn đặt hàng đặt mua những mặt hàng nào và tổng số tiền mà mỗi đơn
đặt hàng phải trả là bao nhiêu?
SELECT A.SOHOADON,B.MAHANG,TENHANG
FROM (DONDATHANG AS A INNER JOIN CHITIETDATHANG AS B ON A.SOHOADON=B.SOHOADON) 
						INNER JOIN MATHANG AS C ON B.MAHANG=C.MAHANG
GROUP BY A.SOHOADON, B.MAHANG, TENHANG
ORDER BY A.SOHOADON
COMPUTE SUM(B.SOLUONG*GIABAN-B.SOLUONG*GIABAN*MUCGIAMGIA/100) BY A.SOHOADON*//
SELECT A.SOHOADON, B.MAHANG, TENHANG,
	SUM(B.SOLUONG*GIABAN-B.SOLUONG*GIABAN*MUCGIAMGIA/100) AS TONGTIEN
FROM (DONDATHANG AS A INNER JOIN CHITIETDATHANG AS B ON A.SOHOADON=B.SOHOADON) 
	INNER JOIN MATHANG AS C ON B.MAHANG=C.MAHANG
GROUP BY A.SOHOADON, B.MAHANG, TENHANG
ORDER BY A.SOHOADON
//*5. 31 Hãy cho biết mỗi một loại hàng bao gồm những mặt hàng nào, tổng số lượng
hàng của mỗi loại và tổng số lượng của tất cả các mặt hàng hiện có trong công ty
là bao nhiêu?*//
SELECT LOAIHANG.MALOAIHANG, TENLOAIHANG, MAHANG, TENHANG,  SUM(SOLUONG) AS TONGSOLUONG
FROM LOAIHANG  JOIN MATHANG ON LOAIHANG.MALOAIHANG=MATHANG.MALOAIHANG
GROUP BY LOAIHANG.MALOAIHANG, TENLOAIHANG, MAHANG, TENHANG
ORDER BY LOAIHANG.MALOAIHANG
//*5. 32 Thống kê xem trong năm 2003, mỗi một mặt hàng trong mỗi tháng và trong cả
năm bán được với số lượng bao nhiêu
Yêu cầu: Kết quả được hiển thị dưới dạng bảng, hai cột cột đầu là mã hàng và
tên hàng, các cột còn lại tương ứng với các tháng từ 1 đến 12 và cả năm. Như
vậy mỗi dòng trong kết quả cho biết số l ượng hàng bán được mỗi tháng và trong
cả năm của mỗi mặt hàng.*//
