--CẤU TRÚC LỒNG NHAU 
--HAVING--
SELECT
FROM
WHERE
GROUP BY 
HAVING <HÀM THỐNG KÊ> >= ALL(SELECT 
							FROM
							WHERE
							GROUP BY)
--TÍNH SỐ LƯƠNGJ MẶT HÀNG BÁN RA NHIỀU NHẤT
--B1. MỖI MẶT HÀNG BÁN RA VỚI SỐ LƯỢNG BAO NHIÊU
SELECT MATHANG.MAHANG, TENHANG, SUM(CHITIETDATHANG.SOLUONG)
FROM MATHANG INNER JOIN CHITIETDATHANG ON CHITIETDATHANG.MAHANG=MATHANG.MAHANG
GROUP BY  MATHANG.MAHANG, TENHANG
HAVING  SUM(CHITIETDATHANG.SOLUONG) >= ALL (SELECT  SUM(CHITIETDATHANG.SOLUONG)
											FROM MATHANG INNER JOIN CHITIETDATHANG ON CHITIETDATHANG.MAHANG=MATHANG.MAHANG
											GROUP BY MATHANG.MAHANG,TENHANG)





SELECT NHANVIEN.MANHANVIEN, HO, TEN ,SUM(CHITIETDATHANG.SOHOADON)
FROM NHANVIEN INNER JOIN DONDATHANG ON NHANVIEN.MANHANVIEN=DONDATHANG.MANHANVIEN
				INNER JOIN CHITIETDATHANG ON CHITIETDATHANG.SOHOADON=DONDATHANG.SOHOADON
GROUP BY NHANVIEN.MANHANVIEN, HO, TEN
HAVING SUM(CHITIETDATHANG.SOHOADON) >= ALL (SELECT  SUM(CHITIETDATHANG.SOHOADON) 
											FROM DONDATHANG INNER JOIN NHANVIEN ON DONDATHANG.MANHANVIEN=NHANVIEN.MANHANVIEN
															INNER JOIN CHITIETDATHANG ON CHITIETDATHANG.SOHOADON=DONDATHANG.SOHOADON
											GROUP BY DONDATHANG.MANHANVIEN , HO ,TEN)


