select *
from CHI_TIET_SU_DUNG_DV
where SOLUONG between 3 and 10

update PHONG
set GIAPHONG=GIAPHONG+10.000
where SOKHACHTOIDA > 10

delete from DAT_PHONG
where TRANGTHAIDAT is 'Da huy'

select TenKH
from KHACH_HANG
where TenKH like '[HNM]%' and LEN(TENKH) <= 20


select distinct TENKH
from KHACH_HANG

select TENKH
from KHACH_HANG 
GROUP BY TENKH

select MADV, TENDV, DONVITINH, DONGIA
from DICH_VU_DI_KEM
where (DONVITINH = 'LON' and DONGIA >= 10.000)
		OR (DONVITINH='CAI' and DONGIA <= 5.000)

select  DAT_PHONG.MADATPHONG, PHONG.MAPHONG,LOAIPHONG, SOKHACHTOIDA, GIAPHONG, KHACH_HANG.MAKH,TENKH, SODT, NGAYDAT, GIOBATDAU, GIOKETTHUC,CHI_TIET_SU_DUNG_DV.MADV,SOLUONG,DONGIA
from DAT_PHONG join PHONG on DAT_PHONG.MAPHONG=PHONG.MAPHONG
				join CHI_TIET_SU_DUNG_DV on CHI_TIET_SU_DUNG_DV.MADATPHONG=DAT_PHONG.MADATPHONG
				join DICH_VU_DI_KEM on DICH_VU_DI_KEM.MADV=CHI_TIET_SU_DUNG_DV.MADV
				join KHACH_HANG on KHACH_HANG.MAKH=DAT_PHONG.MAKH
where (year(NGAYDAT) =2016 or YEAR(NGAYDAT)=2018)
		and GIAPHONG > 50.000 



select DAT_PHONG.MADATPHONG, DAT_PHONG.MAPHONG,LOAIPHONG, GIAPHONG, TENKH,NGAYDAT, 
SUM(GIAPHONG*DATEDIFF(HOUR,GIOBATDAU,GIOKETTHUC)) as TongTienHat,
SUM(SOLUONG*DONGIA) as TongTienSDDV,
SUM((GIAPHONG*DATEDIFF(HOUR,GIOBATDAU,GIOKETTHUC))+(SOLUONG*DONGIA)) AS TONG
from DAT_PHONG join PHONG on DAT_PHONG.MAPHONG=PHONG.MAPHONG
				 join KHACH_HANG on KHACH_HANG.MAKH=DAT_PHONG.MAKH
				 join CHI_TIET_SU_DUNG_DV on CHI_TIET_SU_DUNG_DV.MADATPHONG=DAT_PHONG.MADATPHONG
				  join DICH_VU_DI_KEM on DICH_VU_DI_KEM.MADV=CHI_TIET_SU_DUNG_DV.MADV
GROUP BY DAT_PHONG.MADATPHONG, DAT_PHONG.MAPHONG,LOAIPHONG, GIAPHONG, TENKH,NGAYDAT


SELECT MAKH, TENKH, DIACHI, SODT
FROM KHACH_HANG
WHERE DIACHI='HOA XUAN' AND MAKH IN (SELECT DISTINCT MAKH
									FROM DAT_PHONG)


SELECT PHONG.MAPHONG, LOAIPHONG, SOKHACHTOIDA,GIAPHONG, COUNT(DAT_PHONG.MADATPHONG) AS SOLANDAT
FROM PHONG JOIN DAT_PHONG ON PHONG.MAPHONG=DAT_PHONG.MAPHONG
WHERE TRANGTHAIDAT='DA DAT'
GROUP BY  PHONG.MAPHONG, LOAIPHONG, SOKHACHTOIDA, GIAPHONG
HAVING COUNT(DAT_PHONG.MADATPHONG) >=1
