-- Câu 20, 21, 22, 23, 24, 25, 26---
--20/Tổng số tiền mà khách hàng phải trả cho mỗi đơn đặt hàng là bao nhiêu?--
SELECT DONDATHANG.SOHOADON, DONDATHANG.MAKHACHHANG,TENCONGTY,TENGIAODICH,
		SUM(SOLUONG*GIABAN-SOLUONG*GIABAN*MUCGIAMGIA/100) AS TONGSOTIEN
FROM (KHACHHANG JOIN DONDATHANG ON KHACHHANG.MAKHACHHANG=DONDATHANG.MAKHACHHANG)
				JOIN CHITIETDATHANG ON DONDATHANG.SOHOADON=CHITIETDATHANG.SOHOADON
GROUP BY DONDATHANG.MAKHACHHANG, TENCONGTY,TENGIAODICH,DONDATHANG.SOHOADON
--Trong năm 2017, những mặt hàng nào chỉ được đặt mua đúng một lần.
SELECT MATHANG.MAHANG,TENHANG
FROM (MATHANG JOIN CHITIETDATHANG ON MATHANG.MAHANG=CHITIETDATHANG.MAHANG) 
				JOIN DONDATHANG ON CHITIETDATHANG.SOHOADON=DONDATHANG.SOHOADON
WHERE YEAR(NGAYDATHANG)=2017
GROUP BY MATHANG.MAHANG,TENHANG
HAVING COUNT(CHITIETDATHANG.MAHANG)=1

//* 22 Hãy cho biết mỗi một khách hàng đã phải bỏ ra bao nhiêu tiền để đặt mua hàng
của công ty*//
SELECT KHACHHANG.MAKHACHHANG,TENCONGTY,TENGIAODICH,
SUM( SOLUONG*GIABAN-SOLUONG*GIABAN*MUCGIAMGIA/100) AS TIENDATMUAHANG
FROM (KHACHHANG JOIN DONDATHANG ON KHACHHANG.MAKHACHHANG=DONDATHANG.MAKHACHHANG)
				JOIN CHITIETDATHANG ON DONDATHANG.SOHOADON=CHITIETDATHANG.SOHOADON
GROUP BY KHACHHANG.MAKHACHHANG,TENCONGTY,TENGIAODICH
//*Mỗi một nhân viên của công ty đã lập bao nhiêu đơn đặt hàng (nếu nhân viên
chưa hề lập một hoá đơn nào thì cho kết quả là 0)**//

SELECT NHANVIEN.MANHANVIEN, HO, TEN, COUNT(SOHOADON)  AS SODONDALAP
FROM NHANVIEN JOIN DONDATHANG ON NHANVIEN.MANHANVIEN=DONDATHANG.MANHANVIEN
GROUP BY  NHANVIEN.MANHANVIEN, HO, TEN
//* 24 Cho biết tổng số tiền hàng mà cửa hàng thu được trong mỗi tháng của năm 2003
(thời được gian tính theo ngày đặt hàng).*//

SELECT MONTH(NGAYDATHANG) AS THANG,
		SUM(SOLUONG*GIABAN-SOLUONG*GIABAN*MUCGIAMGIA/100) AS TONGSOTIEN
FROM DONDATHANG INNER JOIN CHITIETDATHANG ON DONDATHANG.SOHOADON=CHITIETDATHANG.SOHOADON
WHERE YEAR(NGAYDATHANG)=2003
GROUP BY MONTH(NGAYDATHANG)

//* 25 Hãy cho biết tổng số tiền lời mà công ty thu được từ mỗi mặt hàng trong năm
2003.*//
SELECT C.MAHANG,TENHANG,
	SUM(B.SOLUONG*GIABAN-B.SOLUONG*GIABAN*MUCGIAMGIA/100)-SUM(B.SOLUONG*GIAHANG) AS TIENLOI
FROM (DONDATHANG as A join CHITIETDATHANG AS B ON A.SOHOADON=B.SOHOADON)
						join MATHANG AS C ON B.MAHANG=C.MAHANG
WHERE YEAR(NGAYDATHANG)=2003
GROUP BY C.MAHANG,TENHANG
//* 26 Hãy cho biết tổng số lượng hàng của mỗi mặt hàng mà công ty đã có (tổng số
lượng hàng hiện có và đã bán).*//
SELECT MATHANG.MAHANG, TENHANG, MATHANG.SOLUONG +
CASE
	WHEN SUM(CHITIETDATHANG.SOLUONG) IS NULL THEN 0
	ELSE SUM(CHITIETDATHANG.SOLUONG)
END AS TONGSOLUONG
FROM MATHANG JOIN CHITIETDATHANG ON MATHANG.MAHANG=CHITIETDATHANG.MAHANG
GROUP BY MATHANG.MAHANG, TENHANG, MATHANG.SOLUONG
